# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionid', models.CharField(blank=True, db_column='QuestionID', max_length=100, null=True)),
                ('personid', models.CharField(blank=True, db_column='PersonID', max_length=100, null=True)),
                ('answerid', models.CharField(blank=True, db_column='AnswerID', max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'answer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Followees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personid', models.CharField(blank=True, max_length=100, null=True)),
                ('id_f', models.IntegerField(blank=True, null=True)),
                ('followeesid', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'followees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personid', models.CharField(db_column='PersonID', max_length=100)),
                ('personhashid', models.CharField(blank=True, db_column='PersonHashID', max_length=100, null=True)),
                ('personname', models.CharField(blank=True, db_column='PersonName', max_length=100, null=True)),
                ('persongender', models.CharField(blank=True, db_column='PersonGender', max_length=100, null=True)),
                ('personbiography', models.CharField(blank=True, db_column='PersonBiography', max_length=100, null=True)),
                ('personaddress', models.CharField(blank=True, db_column='PersonAddress', max_length=100, null=True)),
                ('personbusiness', models.CharField(blank=True, db_column='PersonBusiness', max_length=100, null=True)),
                ('personemployment', models.CharField(blank=True, db_column='PersonEmployment', max_length=100, null=True)),
                ('personposition', models.CharField(blank=True, db_column='PersonPosition', max_length=100, null=True)),
                ('personeducation', models.CharField(blank=True, db_column='PersonEducation', max_length=100, null=True)),
                ('personeducation_extra', models.CharField(blank=True, db_column='PersonEducation_extra', max_length=100, null=True)),
                ('personfolloweesnum', models.IntegerField(blank=True, db_column='PersonFolloweesNum', null=True)),
                ('personfollowersnum', models.IntegerField(blank=True, db_column='PersonFollowersNum', null=True)),
                ('personagreenum', models.IntegerField(blank=True, db_column='PersonAgreeNum', null=True)),
                ('personthanksnum', models.IntegerField(blank=True, db_column='PersonThanksNum', null=True)),
                ('personasksnum', models.IntegerField(blank=True, db_column='PersonAsksNum', null=True)),
                ('personanswersnum', models.IntegerField(blank=True, db_column='PersonAnswersNum', null=True)),
                ('personpostsnum', models.IntegerField(blank=True, db_column='PersonPostsNum', null=True)),
                ('personcollectionsnum', models.IntegerField(blank=True, db_column='PersonCollectionsNum', null=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personid', models.CharField(blank=True, db_column='PersonID', max_length=100, null=True)),
            ],
            options={
                'db_table': 'person_id',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionid', models.CharField(blank=True, db_column='QuestionID', max_length=100, null=True)),
                ('questionname', models.CharField(blank=True, db_column='QuestionName', max_length=100, null=True)),
                ('fromtopicid', models.CharField(blank=True, db_column='FromTopicID', max_length=100, null=True)),
                ('fromtopicname', models.CharField(blank=True, db_column='FromTopicName', max_length=100, null=True)),
            ],
            options={
                'db_table': 'question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_topic', models.CharField(blank=True, db_column='Father_Topic', max_length=100, null=True)),
                ('father_topic_id', models.IntegerField(blank=True, db_column='Father_Topic_ID', null=True)),
                ('child_topic', models.CharField(blank=True, db_column='Child_Topic', max_length=100, null=True)),
                ('child_topic_id', models.IntegerField(blank=True, db_column='Child_Topic_ID', null=True)),
            ],
            options={
                'db_table': 'topic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopicId',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('topicid', models.IntegerField(blank=True, db_column='TopicID', null=True)),
                ('topicname', models.CharField(blank=True, db_column='TopicName', max_length=100, null=True)),
            ],
            options={
                'db_table': 'topic_id',
                'managed': False,
            },
        ),
    ]
